"""empty message

Revision ID: 01fee576b956
Revises: dd9cc2035e53
Create Date: 2020-04-14 16:52:13.777283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01fee576b956'
down_revision = 'dd9cc2035e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('offer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'offer')
    # ### end Alembic commands ###
