"""empty message

Revision ID: 2539583f6c57
Revises: 01fee576b956
Create Date: 2020-04-14 20:53:03.786617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2539583f6c57'
down_revision = '01fee576b956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('expenses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'expenses')
    # ### end Alembic commands ###
