"""empty message

Revision ID: dd9cc2035e53
Revises: 7ca3c196f055
Create Date: 2020-04-13 10:12:52.509450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9cc2035e53'
down_revision = '7ca3c196f055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('password', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'password')
    # ### end Alembic commands ###
